## Creation of arrays using NumPy library 

In [1]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
a = np.array([2,3,4,5])
a
#multi dimensional
a = np.array([(1,2,3,4),(5,6,7,8)])
a

array([2, 3, 4, 5])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
#this will return an error.
#np.array requires an array_like object as first positional parameter
a = np.array(2,3,4,5)
a

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [4]:
#this is perfectly ok
a = np.array([2,3.2,4.1,5])
a

array([2. , 3.2, 4.1, 5. ])

In [5]:
#create an array of zeros
a = np.zeros(5)
a
#create a multidimensional array of ones
a = np.ones([(4),(5)])
a

array([0., 0., 0., 0., 0.])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
#return an array of 1s with same shape and type as supplied array/tuple 
a = np.ones_like((2,3.2,4.1,5,0))
a

#return an array of 0s with same shape and type as supplied array/tuple 
a = np.zeros_like(np.arange(3,9))
a

array([1., 1., 1., 1., 1.])

array([0, 0, 0, 0, 0, 0])

In [26]:
#create a new array without initializing 
a = np.empty([4,2])
a

#create a new array as same shape and type as given array
a = ( (4,2,1),(-1,2,0) )
a = np.empty_like(a)
a

array([[-1.72723371e-077, -1.72723371e-077],
       [ 7.41098469e-323,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000]])

array([[0, 0, 0],
       [0, 0, 0]])

In [38]:
#create a new array of given shape & type initialized with `fill_value`.
a = np.full(np.arange(2,5),9999)
a

#create a full array of same shape & type initialized with `fill_value`.
a = np.full_like( ((-1,4,3,5),(0,3.4,5.2,6.1)),0)
a

array([[[9999, 9999, 9999, 9999],
        [9999, 9999, 9999, 9999],
        [9999, 9999, 9999, 9999]],

       [[9999, 9999, 9999, 9999],
        [9999, 9999, 9999, 9999],
        [9999, 9999, 9999, 9999]]])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
#create a new array of N dimensions with 1's in diagonal
a = np.eye(3,)
a

#create a new array of NxM dimensions with 1's in diagonal
a = np.eye(4,3)
a

#create a new array of NxM dimensions with 1's in diagonal starting from index k
a = np.eye(3,4,k=2)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [52]:
#creates an identity array of N dimensions
#identity array is a swaure array with 1s in diagonal
a = np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
#create an array from 3 to 15 exclusive 
a = np.arange(3,15)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
#create an array from 3 to 15 exclusive with step size of 2
a = np.arange(3,15,2)
a

array([ 3,  5,  7,  9, 11, 13])

In [22]:
#create an array from -2 to 2 with 7 elements
#start,stop,number of elements
a  = np.linspace(-2,2,7)
a

array([-2.        , -1.33333333, -0.66666667,  0.        ,  0.66666667,
        1.33333333,  2.        ])

In [ ]:
a = np.ones