## Creation of arrays using NumPy library 

In [15]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [16]:
a = np.array([2,3,4,5])
a
#multi dimensional
a = np.array([(1,2,3,4),(5,6,7,8)])
a

array([2, 3, 4, 5])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
#this will return an error.
#np.array requires an array_like object as first positional parameter
a = np.array(2,3,4,5)
a

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [18]:
#this is perfectly ok
a = np.array([2,3.2,4.1,5])
a

array([2. , 3.2, 4.1, 5. ])

In [19]:
#create an array of zeros
a = np.zeros(5)
a
#create a multidimensional array of ones
a = np.ones([(4),(5)])
a

array([0., 0., 0., 0., 0.])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
#create an array from 3 to 15 exclusive 
a = np.arange(3,15)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
#create an array from 3 to 15 exclusive with step size of 2
a = np.arange(3,15,2)
a

array([ 3,  5,  7,  9, 11, 13])

In [22]:
#create an array from -2 to 2 with 7 elements
#start,stop,number of elements
a  = np.linspace(-2,2,7)
a

array([-2.        , -1.33333333, -0.66666667,  0.        ,  0.66666667,
        1.33333333,  2.        ])