### Quick introduction to mathematical and statistical methods of Numpy

In [81]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [82]:
#Create an array
arr = np.array(np.linspace(3,15,10))
arr

array([ 3.        ,  4.33333333,  5.66666667,  7.        ,  8.33333333,
        9.66666667, 11.        , 12.33333333, 13.66666667, 15.        ])

In [83]:
#Mean of all the elements in the array
np.mean(arr)

#Calculate by iterating over array w/o using the Numpy library method
mean = 0.0
for i in arr:
    mean += i

mean /= len(arr)
mean

9.0

9.0

In [84]:
#Cumulative sum of all the elements in the array
np.cumsum(arr)

#Cumulative product of all the elements in the array
np.cumprod(arr)

array([ 3.        ,  7.33333333, 13.        , 20.        , 28.33333333,
       38.        , 49.        , 61.33333333, 75.        , 90.        ])

array([3.00000000e+00, 1.30000000e+01, 7.36666667e+01, 5.15666667e+02,
       4.29722222e+03, 4.15398148e+04, 4.56937963e+05, 5.63556821e+06,
       7.70194322e+07, 1.15529148e+09])

In [85]:
# Sum of all elements in the array, min and max in the array
np.sum(arr)
np.min(arr)
np.max(arr)

90.0

3.0

15.0

In [86]:
#Calcualte variance by using wihtout calling Numpy library method
variance = 0.0
for i in arr:
    variance += ((i - arr.mean()) ** 2) / len(arr)
sumofvar

#Variance of array
np.var(arr)

14.666666666666666

14.666666666666666

In [87]:
#Standard deviation with and without Numpy library call
np.sqrt(variance)
np.std(arr)

3.8297084310253524

3.8297084310253524

### Matrix operations

In [88]:
#2D array or matrix
matrix = np.array( ( [1,4,5],[0,7,8],[2,3,6] ) )
matrix

array([[1, 4, 5],
       [0, 7, 8],
       [2, 3, 6]])

In [89]:
#mean of all the elements in the matrix along each row
np.mean(matrix, axis = 1)

#mean of all the elements in the matrix along each column
np.mean(matrix, axis = 0)

array([3.33333333, 5.        , 3.66666667])

array([1.        , 4.66666667, 6.33333333])

In [90]:
#Iterate over matrix
sum = 0.0
numelements = 0
for i in matrix:
    sum += np.sum(i)
    numelements += len(i)

mean = sum/numelements
mean

#Numpy library call to calcualte mean of all the elements in the matrix
np.mean(matrix)

4.0

4.0

In [91]:
#Numpy library call to calcualte standard deviation of the matrix
np.std(matrix)

2.581988897471611

In [92]:
#min element in the matrix along each row
np.min(matrix,axis=0)

#min element in the matrix along each column
np.min(matrix,axis=1)

#min element in the entire matrix
np.min(matrix)

array([0, 3, 5])

array([1, 0, 2])

0

In [93]:
#cumlative sum of all the elements in the matrix
np.cumsum(matrix)

array([ 1,  5, 10, 10, 17, 25, 27, 30, 36])

In [94]:
#cumlative sum of all the elements in the matrix along each row
np.cumsum(matrix,axis = 1)

#cumlative sum of all the elements in the matrix along each column
np.cumsum(matrix,axis = 0)

array([[ 1,  5, 10],
       [ 0,  7, 15],
       [ 2,  5, 11]])

array([[ 1,  4,  5],
       [ 1, 11, 13],
       [ 3, 14, 19]])

In [95]:
#cumlative product of all the elements in the matrix
np.cumprod(matrix)

array([ 1,  4, 20,  0,  0,  0,  0,  0,  0])

In [96]:
#cumlative product of all the elements in the matrix along each row
np.cumprod(matrix,axis = 1)

#cumlative product of all the elements in the matrix along each column
np.cumprod(matrix,axis = 0)

array([[ 1,  4, 20],
       [ 0,  0,  0],
       [ 2,  6, 36]])

array([[  1,   4,   5],
       [  0,  28,  40],
       [  0,  84, 240]])