In [122]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### A universal function (ufuncs) performs operations on each element of numpy array(ndarray)
### There are two kinds of ufuncs; unary and binary
### unary ufuncs operate on each element of a single numpy array
### binary ufuncs perform element wise operations on two numpy arrays


## Some examples of unary universal functions (ufuncs)

In [123]:
a = np.linspace(3,33,10,dtype=int)
a

array([ 3,  6,  9, 13, 16, 19, 23, 26, 29, 33])

In [124]:
np.sqrt(a)

array([1.73205081, 2.44948974, 3.        , 3.60555128, 4.        ,
       4.35889894, 4.79583152, 5.09901951, 5.38516481, 5.74456265])

In [125]:
np.exp(a)

array([2.00855369e+01, 4.03428793e+02, 8.10308393e+03, 4.42413392e+05,
       8.88611052e+06, 1.78482301e+08, 9.74480345e+09, 1.95729609e+11,
       3.93133430e+12, 2.14643580e+14])

In [126]:
np.sign(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [127]:
np.log(a)

array([1.09861229, 1.79175947, 2.19722458, 2.56494936, 2.77258872,
       2.94443898, 3.13549422, 3.25809654, 3.36729583, 3.49650756])

In [128]:
np.log10(a)

array([0.47712125, 0.77815125, 0.95424251, 1.11394335, 1.20411998,
       1.2787536 , 1.36172784, 1.41497335, 1.462398  , 1.51851394])

In [129]:
np.square(a)

array([   9,   36,   81,  169,  256,  361,  529,  676,  841, 1089])

In [130]:
np.isnan(a)

array([False, False, False, False, False, False, False, False, False,
       False])

In [131]:
np.abs(a)

array([ 3,  6,  9, 13, 16, 19, 23, 26, 29, 33])

## Some examples of binary universal functions (ufuncs)

In [135]:
array1 = np.linspace(1,15,10)
array2 = np.linspace(1,12,10)

In [136]:
array1
array2

array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
        8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ])

array([ 1.        ,  2.22222222,  3.44444444,  4.66666667,  5.88888889,
        7.11111111,  8.33333333,  9.55555556, 10.77777778, 12.        ])

In [138]:
np.add(array1,array2)

array([ 2.        ,  4.77777778,  7.55555556, 10.33333333, 13.11111111,
       15.88888889, 18.66666667, 21.44444444, 24.22222222, 27.        ])

In [139]:
np.multiply(array1,array2)

array([  1.        ,   5.67901235,  14.16049383,  26.44444444,
        42.5308642 ,  62.41975309,  86.11111111, 113.60493827,
       144.90123457, 180.        ])

In [141]:
np.mod(array1,array2)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [142]:
np.divide(array1,array2)

array([1.        , 1.15      , 1.19354839, 1.21428571, 1.22641509,
       1.234375  , 1.24      , 1.24418605, 1.24742268, 1.25      ])

In [146]:
np.equal(array1,array2)
np.not_equal(array1,array2)

array([ True, False, False, False, False, False, False, False, False,
       False])

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [143]:
np.greater(array1,array2)# element wise comparison returns a boolean array

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])