### Basic matrix operations in Numpy

In [1]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
#2D array or matrix
matrix = np.array( ( [1,4,5],[0,7,8],[2,3,6] ) )
matrix

array([[1, 4, 5],
       [0, 7, 8],
       [2, 3, 6]])

In [3]:
matrix.flatten()

array([1, 4, 5, 0, 7, 8, 2, 3, 6])

In [5]:
matrix.diagonal()

array([1, 7, 6])

In [7]:
matrix.diagonal().sum()

14

In [17]:
#determinant of a matrix
np.linalg.det(matrix)

12.0

In [9]:
# Rank of a matrix is equal to number of unique rows and columns in the matrix (unique = not made of other rows or columns)
np.linalg.matrix_rank(matrix)

3

In [13]:
#For a square matrix & psotive N (2 in this example), power of matrix is defined by multiplying the matrix by itself N times
np.linalg.matrix_power(matrix,2)

array([[ 11,  47,  67],
       [ 16,  73, 104],
       [ 14,  47,  70]])

In [14]:
np.linalg.inv(matrix)

array([[ 1.5       , -0.75      , -0.25      ],
       [ 1.33333333, -0.33333333, -0.66666667],
       [-1.16666667,  0.41666667,  0.58333333]])

In [16]:
matrix_a = np.array( [ [2,3,6],[1,4,5],[0,7,8]] )
matrix_a

array([[2, 3, 6],
       [1, 4, 5],
       [0, 7, 8]])

In [18]:
#dot product of matrices
np.dot(matrix,matrix_a)

array([[ 6, 54, 66],
       [ 7, 84, 99],
       [ 7, 60, 75]])